# Generated by Django 2.2.24 on 2023-03-29 10:55

from django.db import migrations

def set_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20230328_1804'),
    ]
    operations = [
        migrations.RunPython(set_new_building)
    ]
